In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
num_1 = np.array([1,2,3, 4, 5])
num_1

array([1, 2, 3, 4, 5])

In [4]:
type(num_1)

numpy.ndarray

In [5]:
len(num_1)

5

In [6]:
print(num_1)

[1 2 3 4 5]


In [7]:
num_1[-3:-1]

array([3, 4])

In [8]:
num_1[1:4]

array([2, 3, 4])

In [9]:
num_1.ndim

1

#### Two dimentional array

In [13]:
import numpy 

arr1 = numpy.array([[1,2,3],[4,5,6]])

arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr1.ndim

2

In [15]:
arr1[1][1]

5

In [16]:
import numpy as np

arr2 = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[7,8,9]]])

print(arr2)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]]]


In [18]:
arr2.ndim
arr2.shape

(2, 2, 3)

In [23]:
from numpy import random
x = random.randint(100)
print(x)

93


In [24]:
x = random.rand()
print(x)

0.9191026045282857


In [26]:
from numpy import random

#x = random.randint(100, size=(5))

x = random.randint(100, size=(3,5))

print(x)

[[ 2 81 87  4 53]
 [43 83 84 99 55]
 [52 44  0 91 74]]


In [28]:
from numpy import random

x = random.choice([3,5,7,9], size=(3,5))

print(x)

[[7 7 3 5 5]
 [3 5 9 7 3]
 [5 3 5 3 5]]


#### Random permutations and shuffle

In [29]:
from numpy import random
import numpy as np

arr = np.array([1,2,3,4,5])

random.shuffle(arr)   #the shuffle() method makes changes to the original array

print(arr)

[1 4 2 5 3]


In [33]:
#pumutations

from numpy import random 
import numpy as np

arr = np.array([1,2,3,4,5])

print(random.permutation(arr)) #permutation() method return a re-arraged arry and li

[5 2 4 1 3]
